<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductVariantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('product_variants')->delete();
        
        DB::table('product_variants')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 3,
                'sku' => 'PERM-003-S',
                'name' => 'CLSU Tumbler Green',
                'price' => '44.99',
                'stock_quantity' => 5,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 14:30:57',
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 3,
                'sku' => 'PERM-003-M',
                'name' => 'CLSU Tumbler Yellow',
                'price' => '750.00',
                'stock_quantity' => 5,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 14:30:57',
            ),
            2 => 
            array (
                'id' => 4,
                'product_id' => 6,
                'sku' => 'PERM-006-S',
                'name' => 'CLSU Athletes Hoodie - Small',
                'price' => '899.00',
                'stock_quantity' => 0,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 15:53:11',
            ),
            3 => 
            array (
                'id' => 5,
                'product_id' => 6,
                'sku' => 'PERM-006-M',
                'name' => 'CLSU Athletes Hoodie - Medium',
                'price' => '899.00',
                'stock_quantity' => 0,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 15:53:11',
            ),
            4 => 
            array (
                'id' => 6,
                'product_id' => 6,
                'sku' => 'PERM-006-L',
                'name' => 'CLSU Athletes Hoodie - Large',
                'price' => '899.00',
                'stock_quantity' => 1,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 15:53:11',
            ),
            5 => 
            array (
                'id' => 7,
                'product_id' => 9,
                'sku' => 'PERM-009-S',
                'name' => 'Permanent System Product 9 - Small',
                'price' => '74.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            6 => 
            array (
                'id' => 8,
                'product_id' => 9,
                'sku' => 'PERM-009-M',
                'name' => 'Permanent System Product 9 - Medium',
                'price' => '74.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            7 => 
            array (
                'id' => 9,
                'product_id' => 9,
                'sku' => 'PERM-009-L',
                'name' => 'Permanent System Product 9 - Large',
                'price' => '74.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            8 => 
            array (
                'id' => 10,
                'product_id' => 12,
                'sku' => 'PERM-012-S',
                'name' => 'Permanent System Product 12 - Small',
                'price' => '89.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            9 => 
            array (
                'id' => 11,
                'product_id' => 12,
                'sku' => 'PERM-012-M',
                'name' => 'Permanent System Product 12 - Medium',
                'price' => '89.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            10 => 
            array (
                'id' => 12,
                'product_id' => 12,
                'sku' => 'PERM-012-L',
                'name' => 'Permanent System Product 12 - Large',
                'price' => '89.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            11 => 
            array (
                'id' => 13,
                'product_id' => 15,
                'sku' => 'PERM-015-S',
                'name' => 'Permanent System Product 15 - Small',
                'price' => '104.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            12 => 
            array (
                'id' => 14,
                'product_id' => 15,
                'sku' => 'PERM-015-M',
                'name' => 'Permanent System Product 15 - Medium',
                'price' => '104.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            13 => 
            array (
                'id' => 15,
                'product_id' => 15,
                'sku' => 'PERM-015-L',
                'name' => 'Permanent System Product 15 - Large',
                'price' => '104.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            14 => 
            array (
                'id' => 16,
                'product_id' => 18,
                'sku' => 'PERM-018-S',
                'name' => 'Permanent System Product 18 - Small',
                'price' => '119.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            15 => 
            array (
                'id' => 17,
                'product_id' => 18,
                'sku' => 'PERM-018-M',
                'name' => 'Permanent System Product 18 - Medium',
                'price' => '119.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            16 => 
            array (
                'id' => 18,
                'product_id' => 18,
                'sku' => 'PERM-018-L',
                'name' => 'Permanent System Product 18 - Large',
                'price' => '119.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            17 => 
            array (
                'id' => 19,
                'product_id' => 21,
                'sku' => 'PERM-021-S',
                'name' => 'Permanent System Product 21 - Small',
                'price' => '134.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            18 => 
            array (
                'id' => 20,
                'product_id' => 21,
                'sku' => 'PERM-021-M',
                'name' => 'Permanent System Product 21 - Medium',
                'price' => '134.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            19 => 
            array (
                'id' => 21,
                'product_id' => 21,
                'sku' => 'PERM-021-L',
                'name' => 'Permanent System Product 21 - Large',
                'price' => '134.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            20 => 
            array (
                'id' => 22,
                'product_id' => 24,
                'sku' => 'PERM-024-S',
                'name' => 'Permanent System Product 24 - Small',
                'price' => '149.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            21 => 
            array (
                'id' => 23,
                'product_id' => 24,
                'sku' => 'PERM-024-M',
                'name' => 'Permanent System Product 24 - Medium',
                'price' => '149.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            22 => 
            array (
                'id' => 24,
                'product_id' => 24,
                'sku' => 'PERM-024-L',
                'name' => 'Permanent System Product 24 - Large',
                'price' => '149.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            23 => 
            array (
                'id' => 25,
                'product_id' => 27,
                'sku' => 'PERM-027-S',
                'name' => 'Permanent System Product 27 - Small',
                'price' => '164.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            24 => 
            array (
                'id' => 26,
                'product_id' => 27,
                'sku' => 'PERM-027-M',
                'name' => 'Permanent System Product 27 - Medium',
                'price' => '164.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            25 => 
            array (
                'id' => 27,
                'product_id' => 27,
                'sku' => 'PERM-027-L',
                'name' => 'Permanent System Product 27 - Large',
                'price' => '164.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            26 => 
            array (
                'id' => 28,
                'product_id' => 30,
                'sku' => 'PERM-030-S',
                'name' => 'Permanent System Product 30 - Small',
                'price' => '179.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            27 => 
            array (
                'id' => 29,
                'product_id' => 30,
                'sku' => 'PERM-030-M',
                'name' => 'Permanent System Product 30 - Medium',
                'price' => '179.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            28 => 
            array (
                'id' => 30,
                'product_id' => 30,
                'sku' => 'PERM-030-L',
                'name' => 'Permanent System Product 30 - Large',
                'price' => '179.99',
                'stock_quantity' => 50,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            29 => 
            array (
                'id' => 31,
                'product_id' => 1,
                'sku' => 'VAR-UMSDFQVV',
                'name' => 'Black',
                'price' => '250.00',
                'stock_quantity' => 5,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:47:20',
                'updated_at' => '2026-08-20 13:47:20',
            ),
            30 => 
            array (
                'id' => 32,
                'product_id' => 1,
                'sku' => 'VAR-YZARQV0F',
                'name' => 'Brown',
                'price' => '250.00',
                'stock_quantity' => 3,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:47:20',
                'updated_at' => '2026-08-20 13:47:20',
            ),
            31 => 
            array (
                'id' => 33,
                'product_id' => 1,
                'sku' => 'VAR-JUHLINGF',
                'name' => 'Olive Green',
                'price' => '250.00',
                'stock_quantity' => 4,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:47:20',
                'updated_at' => '2026-08-20 13:47:20',
            ),
            32 => 
            array (
                'id' => 34,
                'product_id' => 1,
                'sku' => 'VAR-AUA0ZUGY',
                'name' => 'White',
                'price' => '250.00',
                'stock_quantity' => 2,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:47:20',
                'updated_at' => '2026-08-20 13:47:20',
            ),
            33 => 
            array (
                'id' => 35,
                'product_id' => 2,
                'sku' => 'VAR-XKDSEPAN',
                'name' => 'Tatak CLSU',
                'price' => '250.00',
                'stock_quantity' => 2,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:13:23',
                'updated_at' => '2026-08-20 14:13:23',
            ),
            34 => 
            array (
                'id' => 36,
                'product_id' => 2,
                'sku' => 'VAR-YESGLDSD',
                'name' => 'Brown Baybayin',
                'price' => '250.00',
                'stock_quantity' => 4,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:13:23',
                'updated_at' => '2026-08-20 14:13:23',
            ),
            35 => 
            array (
                'id' => 37,
                'product_id' => 2,
                'sku' => 'VAR-EWZ20SUG',
                'name' => 'Black Baybayin',
                'price' => '250.00',
                'stock_quantity' => 2,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:14:37',
                'updated_at' => '2026-08-20 14:14:37',
            ),
            36 => 
            array (
                'id' => 38,
                'product_id' => 2,
                'sku' => 'VAR-E56A3NYO',
                'name' => 'Brown and Black Baybayin',
                'price' => '250.00',
                'stock_quantity' => 2,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:14:37',
                'updated_at' => '2026-08-20 14:14:37',
            ),
            37 => 
            array (
                'id' => 39,
                'product_id' => 4,
                'sku' => 'VAR-CPQHQPTJ',
                'name' => 'Black ',
                'price' => '350.00',
                'stock_quantity' => 5,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:41:13',
                'updated_at' => '2026-08-20 14:41:51',
            ),
            38 => 
            array (
                'id' => 40,
                'product_id' => 4,
                'sku' => 'VAR-ROQMVF9N',
                'name' => 'White',
                'price' => '350.00',
                'stock_quantity' => 5,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:41:51',
                'updated_at' => '2026-08-20 14:41:51',
            ),
            39 => 
            array (
                'id' => 41,
                'product_id' => 5,
                'sku' => 'VAR-OSRLJ9XS',
                'name' => 'CLSU Windbreaker - Large',
                'price' => '899.00',
                'stock_quantity' => 1,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 15:09:09',
                'updated_at' => '2026-08-20 15:54:57',
            ),
            40 => 
            array (
                'id' => 42,
                'product_id' => 5,
                'sku' => 'VAR-ABBLKWJA',
                'name' => 'CLSU Windbreaker - XLarge',
                'price' => '899.00',
                'stock_quantity' => 0,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 15:09:09',
                'updated_at' => '2026-08-20 15:56:56',
            ),
            41 => 
            array (
                'id' => 43,
                'product_id' => 7,
                'sku' => 'VAR-KB0C8RN0',
                'name' => 'Honor and Glory - Small',
                'price' => '250.00',
                'stock_quantity' => 0,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:01:51',
                'updated_at' => '2026-08-20 16:01:51',
            ),
            42 => 
            array (
                'id' => 44,
                'product_id' => 7,
                'sku' => 'VAR-A8RLNI9E',
                'name' => 'Honor and Glory - Medium',
                'price' => '250.00',
                'stock_quantity' => 0,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:01:51',
                'updated_at' => '2026-08-20 16:01:51',
            ),
            43 => 
            array (
                'id' => 45,
                'product_id' => 7,
                'sku' => 'VAR-NDLHXOGR',
                'name' => 'Honor and Glory - Large',
                'price' => '250.00',
                'stock_quantity' => 10,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:01:51',
                'updated_at' => '2026-08-20 16:01:51',
            ),
            44 => 
            array (
                'id' => 46,
                'product_id' => 8,
                'sku' => 'VAR-RLNR5RSC',
                'name' => 'CLSU Notebook - Yellow',
                'price' => '80.00',
                'stock_quantity' => 3,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:10:00',
                'updated_at' => '2026-08-20 16:10:00',
            ),
            45 => 
            array (
                'id' => 47,
                'product_id' => 8,
                'sku' => 'VAR-FSETNRBJ',
                'name' => 'CLSU Notebook - Gray',
                'price' => '80.00',
                'stock_quantity' => 3,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:10:00',
                'updated_at' => '2026-08-20 16:10:00',
            ),
            46 => 
            array (
                'id' => 48,
                'product_id' => 8,
                'sku' => 'VAR-87HASTRC',
                'name' => 'CLSU Notebook - Green',
                'price' => '80.00',
                'stock_quantity' => 5,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:10:00',
                'updated_at' => '2026-08-20 16:10:00',
            ),
        ));
    }
}