<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductImagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_images')->delete();
        
        \DB::table('product_images')->insert(array (
            0 => 
            array (
                'id' => 17,
                'product_id' => 9,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-9-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            1 => 
            array (
                'id' => 18,
                'product_id' => 9,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-9-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            2 => 
            array (
                'id' => 19,
                'product_id' => 10,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-10-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            3 => 
            array (
                'id' => 20,
                'product_id' => 10,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-10-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            4 => 
            array (
                'id' => 21,
                'product_id' => 11,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-11-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            5 => 
            array (
                'id' => 22,
                'product_id' => 11,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-11-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            6 => 
            array (
                'id' => 23,
                'product_id' => 12,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-12-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            7 => 
            array (
                'id' => 24,
                'product_id' => 12,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-12-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            8 => 
            array (
                'id' => 25,
                'product_id' => 13,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-13-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            9 => 
            array (
                'id' => 26,
                'product_id' => 13,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-13-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            10 => 
            array (
                'id' => 27,
                'product_id' => 14,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-14-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            11 => 
            array (
                'id' => 28,
                'product_id' => 14,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-14-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            12 => 
            array (
                'id' => 29,
                'product_id' => 15,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-15-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            13 => 
            array (
                'id' => 30,
                'product_id' => 15,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-15-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            14 => 
            array (
                'id' => 31,
                'product_id' => 16,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-16-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            15 => 
            array (
                'id' => 32,
                'product_id' => 16,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-16-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            16 => 
            array (
                'id' => 33,
                'product_id' => 17,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-17-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            17 => 
            array (
                'id' => 34,
                'product_id' => 17,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-17-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            18 => 
            array (
                'id' => 35,
                'product_id' => 18,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-18-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            19 => 
            array (
                'id' => 36,
                'product_id' => 18,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-18-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            20 => 
            array (
                'id' => 37,
                'product_id' => 19,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-19-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            21 => 
            array (
                'id' => 38,
                'product_id' => 19,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-19-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            22 => 
            array (
                'id' => 39,
                'product_id' => 20,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-20-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            23 => 
            array (
                'id' => 40,
                'product_id' => 20,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-20-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            24 => 
            array (
                'id' => 41,
                'product_id' => 21,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-21-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            25 => 
            array (
                'id' => 42,
                'product_id' => 21,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-21-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            26 => 
            array (
                'id' => 43,
                'product_id' => 22,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-22-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            27 => 
            array (
                'id' => 44,
                'product_id' => 22,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-22-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            28 => 
            array (
                'id' => 45,
                'product_id' => 23,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-23-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            29 => 
            array (
                'id' => 46,
                'product_id' => 23,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-23-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            30 => 
            array (
                'id' => 47,
                'product_id' => 24,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-24-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            31 => 
            array (
                'id' => 48,
                'product_id' => 24,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-24-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            32 => 
            array (
                'id' => 49,
                'product_id' => 25,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-25-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            33 => 
            array (
                'id' => 50,
                'product_id' => 25,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-25-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            34 => 
            array (
                'id' => 51,
                'product_id' => 26,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-26-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            35 => 
            array (
                'id' => 52,
                'product_id' => 26,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-26-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            36 => 
            array (
                'id' => 53,
                'product_id' => 27,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-27-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            37 => 
            array (
                'id' => 54,
                'product_id' => 27,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-27-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            38 => 
            array (
                'id' => 55,
                'product_id' => 28,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-28-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            39 => 
            array (
                'id' => 56,
                'product_id' => 28,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-28-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            40 => 
            array (
                'id' => 57,
                'product_id' => 29,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-29-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            41 => 
            array (
                'id' => 58,
                'product_id' => 29,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-29-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            42 => 
            array (
                'id' => 59,
                'product_id' => 30,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-30-1.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            43 => 
            array (
                'id' => 60,
                'product_id' => 30,
                'product_variant_id' => NULL,
                'image_path' => 'products/permanent/product-30-2.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
            ),
            44 => 
            array (
                'id' => 81,
                'product_id' => 1,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FQZ1QAA90DPZ5K8K5N3NM3.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:07:33',
                'updated_at' => '2026-08-20 14:07:33',
            ),
            45 => 
            array (
                'id' => 82,
                'product_id' => 1,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FQZ31NME5WH50HHX6J9RXK.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 14:07:33',
                'updated_at' => '2026-08-20 14:07:33',
            ),
            46 => 
            array (
                'id' => 83,
                'product_id' => 1,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FQZ4CK1GQRFGMX9BVRPEQB.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 2,
                'created_at' => '2026-08-20 14:07:33',
                'updated_at' => '2026-08-20 14:07:33',
            ),
            47 => 
            array (
                'id' => 84,
                'product_id' => 1,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FQZ74W7FT12Y7KWA66JWPR.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 3,
                'created_at' => '2026-08-20 14:07:33',
                'updated_at' => '2026-08-20 14:07:33',
            ),
            48 => 
            array (
                'id' => 93,
                'product_id' => 2,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FRGB5W3F5PTQKJ1CGQQF9R.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:17:00',
                'updated_at' => '2026-08-20 14:17:00',
            ),
            49 => 
            array (
                'id' => 94,
                'product_id' => 2,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FRGCBFW4DK2NMSPVBP6ZQT.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 14:17:00',
                'updated_at' => '2026-08-20 14:17:00',
            ),
            50 => 
            array (
                'id' => 95,
                'product_id' => 2,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FRGDH7ZXCRAHFEFXBT6XK7.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 2,
                'created_at' => '2026-08-20 14:17:00',
                'updated_at' => '2026-08-20 14:17:00',
            ),
            51 => 
            array (
                'id' => 96,
                'product_id' => 2,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FRGEFK97QFAF3MZTXT6RNZ.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 3,
                'created_at' => '2026-08-20 14:17:00',
                'updated_at' => '2026-08-20 14:17:00',
            ),
            52 => 
            array (
                'id' => 97,
                'product_id' => 3,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FSA0TWP16GAKFD5HZ0PG7A.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 14:30:57',
                'updated_at' => '2026-08-20 14:30:57',
            ),
            53 => 
            array (
                'id' => 98,
                'product_id' => 3,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FSA2248YKFX29N8NJVJYQR.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 14:30:57',
                'updated_at' => '2026-08-20 14:30:57',
            ),
            54 => 
            array (
                'id' => 129,
                'product_id' => 4,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FVV8VEKED75DMA3X5KJVBP.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 15:15:19',
                'updated_at' => '2026-08-20 15:15:19',
            ),
            55 => 
            array (
                'id' => 130,
                'product_id' => 4,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FVV9PG7TEG1DEN6AWMNJSD.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 15:15:19',
                'updated_at' => '2026-08-20 15:15:19',
            ),
            56 => 
            array (
                'id' => 154,
                'product_id' => 6,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FY0MTZFJMP8JMPYNQ1MPZ8.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 15:53:11',
                'updated_at' => '2026-08-20 15:53:11',
            ),
            57 => 
            array (
                'id' => 160,
                'product_id' => 5,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FY9YZXXRV41NYEKVA6DGB9.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 15:58:17',
                'updated_at' => '2026-08-20 15:58:17',
            ),
            58 => 
            array (
                'id' => 161,
                'product_id' => 7,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FYGFV44D232NFV14SMENDV.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:01:51',
                'updated_at' => '2026-08-20 16:01:51',
            ),
            59 => 
            array (
                'id' => 165,
                'product_id' => 8,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FZM01EJQVRAH61XTSTFDZM.jpg',
                'alt_text' => NULL,
                'is_primary' => 1,
                'sort_order' => 0,
                'created_at' => '2026-08-20 16:21:15',
                'updated_at' => '2026-08-20 16:21:15',
            ),
            60 => 
            array (
                'id' => 166,
                'product_id' => 8,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FZM1N643APT1PHGP2WGX4P.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 1,
                'created_at' => '2026-08-20 16:21:15',
                'updated_at' => '2026-08-20 16:21:15',
            ),
            61 => 
            array (
                'id' => 167,
                'product_id' => 8,
                'product_variant_id' => NULL,
                'image_path' => 'products/01M0FZM23RVMHCQS3BVEMGJY5R.jpg',
                'alt_text' => NULL,
                'is_primary' => 0,
                'sort_order' => 2,
                'created_at' => '2026-08-20 16:21:15',
                'updated_at' => '2026-08-20 16:21:15',
            ),
        ));
        
        
    }
}