<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('products')->delete();
        
        DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'name' => 'Baybayin T-Shirt v1 ',
                'slug' => 'permanent-system-product-1',
                'sku' => 'PERM-001',
                'short_description' => 'Colored tee featuring bold Baybayin script design',
                'description' => '<p>A classic colored shirt printed with the Sielesyuan design in Baybayin script, celebrating Filipino heritage and CLSU pride. Made from soft, breathable cotton fabric, perfect for everyday wear or campus events.</p>',
                'price' => '250.00',
                'stock_quantity' => 20,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 1,
                'has_variants' => 1,
                'views_count' => 18,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 14:15:27',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 2,
                'name' => 'Enamel CLSU Mugs',
                'slug' => 'permanent-system-product-2',
                'sku' => 'PERM-002',
                'short_description' => 'Enamel mug with CLSU branding',
                'description' => '<p>A classic enamel mug featuring the CLSU logo, combining durability with a nostalgic, vintage-inspired design. Great for coffee, tea, or camping trips.</p>',
                'price' => '250.00',
                'stock_quantity' => 10,
                'low_stock_threshold' => 3,
                'is_active' => 1,
                'is_featured' => 1,
                'has_variants' => 1,
                'views_count' => 3,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 14:51:49',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 2,
                'name' => 'CLSU Tumbler',
                'slug' => 'clsu-tumbler',
                'sku' => 'PERM-003',
                'short_description' => 'Tumbler with CLSU branding',
                'description' => '<p>A durable tumbler featuring the CLSU logo, designed to keep beverages at the right temperature throughout the day. A practical and stylish accessory for campus life.</p>',
                'price' => '750.00',
                'stock_quantity' => 10,
                'low_stock_threshold' => 3,
                'is_active' => 1,
                'is_featured' => 1,
                'has_variants' => 1,
                'views_count' => 3,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 14:58:45',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'name' => 'Sielesyuan Tshirt',
                'slug' => 'permanent-system-product-4',
                'sku' => 'PERM-004',
                'short_description' => 'Classic Sielesyuan design tee',
                'description' => '<p>The original Sielesyuan shirt, featuring a design that reflects Filipino culture and CLSU identity. Comfortable and versatile, perfect for daily wear.</p>',
                'price' => '350.00',
                'stock_quantity' => 30,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 1,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 14:41:51',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 1,
                'name' => 'CLSU Windbreaker',
                'slug' => 'permanent-system-product-5',
                'sku' => 'PERM-005',
                'short_description' => 'Lightweight windbreaker with CLSU print',
                'description' => '<p>A lightweight and functional windbreaker jacket featuring the CLSU design, perfect for outdoor activities, rainy days, or casual campus wear.</p>',
                'price' => '899.00',
                'stock_quantity' => 3,
                'low_stock_threshold' => 2,
                'is_active' => 1,
                'is_featured' => 1,
                'has_variants' => 1,
                'views_count' => 1,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 15:56:56',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 1,
                'name' => 'CLSU Athletes Hoodie',
                'slug' => 'permanent-system-product-6',
                'sku' => 'PERM-006',
                'short_description' => 'Cozy green hoodie with Cobra-themed print',
                'description' => '<p>A warm and comfortable hoodie in green, featuring the Cobra design that represents school spirit. Perfect for cool mornings, late-night studying, or showing your CLSU pride.</p>',
                'price' => '899.00',
                'stock_quantity' => 1,
                'low_stock_threshold' => 2,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 12,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 16:54:04',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 1,
                'name' => 'Glory and Honor Shirt',
                'slug' => 'glory-and-honor-shirt',
                'sku' => 'PERM-007',
                'short_description' => 'Shirt inspired by CLSU\'s motto',
                'description' => '<p>A shirt inspired by the university&#039;s values, featuring the &quot;Glory and Honor&quot; print. A meaningful piece for students who take pride in their alma mater&#039;s legacy and achievements.</p>',
                'price' => '250.00',
                'stock_quantity' => 10,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 16:01:51',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 4,
                'name' => 'CLSU Notebook',
                'slug' => 'clsu-notebook',
                'sku' => 'PERM-008',
                'short_description' => 'Notebook with CLSU cover design',
                'description' => '<p>A high-quality notebook featuring the CLSU design on its cover, perfect for note-taking, journaling, or sketching. A must-have for students who want functional yet school-spirited stationery.</p>',
                'price' => '80.00',
                'stock_quantity' => 20,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 16:10:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 2,
                'name' => 'Permanent System Product 9',
                'slug' => 'permanent-system-product-9',
                'sku' => 'PERM-009',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '74.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 2,
                'name' => 'Permanent System Product 10',
                'slug' => 'permanent-system-product-10',
                'sku' => 'PERM-010',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '79.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 2,
                'name' => 'Permanent System Product 11',
                'slug' => 'permanent-system-product-11',
                'sku' => 'PERM-011',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '84.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 2,
                'name' => 'Permanent System Product 12',
                'slug' => 'permanent-system-product-12',
                'sku' => 'PERM-012',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '89.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 2,
                'name' => 'Permanent System Product 13',
                'slug' => 'permanent-system-product-13',
                'sku' => 'PERM-013',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '94.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 2,
                'name' => 'Permanent System Product 14',
                'slug' => 'permanent-system-product-14',
                'sku' => 'PERM-014',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '99.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 2,
                'name' => 'Permanent System Product 15',
                'slug' => 'permanent-system-product-15',
                'sku' => 'PERM-015',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '104.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 3,
                'name' => 'Permanent System Product 16',
                'slug' => 'permanent-system-product-16',
                'sku' => 'PERM-016',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '109.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 3,
                'name' => 'Permanent System Product 17',
                'slug' => 'permanent-system-product-17',
                'sku' => 'PERM-017',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '114.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 3,
                'name' => 'Permanent System Product 18',
                'slug' => 'permanent-system-product-18',
                'sku' => 'PERM-018',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '119.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 3,
                'name' => 'Permanent System Product 19',
                'slug' => 'permanent-system-product-19',
                'sku' => 'PERM-019',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '124.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 3,
                'name' => 'Permanent System Product 20',
                'slug' => 'permanent-system-product-20',
                'sku' => 'PERM-020',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '129.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 3,
                'name' => 'Permanent System Product 21',
                'slug' => 'permanent-system-product-21',
                'sku' => 'PERM-021',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '134.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 3,
                'name' => 'Permanent System Product 22',
                'slug' => 'permanent-system-product-22',
                'sku' => 'PERM-022',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '139.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 4,
                'name' => 'Permanent System Product 23',
                'slug' => 'permanent-system-product-23',
                'sku' => 'PERM-023',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '144.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 4,
                'name' => 'Permanent System Product 24',
                'slug' => 'permanent-system-product-24',
                'sku' => 'PERM-024',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '149.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 4,
                'name' => 'Permanent System Product 25',
                'slug' => 'permanent-system-product-25',
                'sku' => 'PERM-025',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '154.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 4,
                'name' => 'Permanent System Product 26',
                'slug' => 'permanent-system-product-26',
                'sku' => 'PERM-026',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '159.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 4,
                'name' => 'Permanent System Product 27',
                'slug' => 'permanent-system-product-27',
                'sku' => 'PERM-027',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '164.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 4,
                'name' => 'Permanent System Product 28',
                'slug' => 'permanent-system-product-28',
                'sku' => 'PERM-028',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '169.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 4,
                'name' => 'Permanent System Product 29',
                'slug' => 'permanent-system-product-29',
                'sku' => 'PERM-029',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '174.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 0,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 4,
                'name' => 'Permanent System Product 30',
                'slug' => 'permanent-system-product-30',
                'sku' => 'PERM-030',
                'short_description' => NULL,
                'description' => NULL,
                'price' => '179.99',
                'stock_quantity' => 100,
                'low_stock_threshold' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'has_variants' => 1,
                'views_count' => 0,
                'created_at' => '2026-08-20 13:25:05',
                'updated_at' => '2026-08-20 13:25:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}