<?php

namespace App\Filament\Resources\Categories\Pages\Concerns;

use App\Models\Category;
use App\Rules\UniqueCategoryName;
use Filament\Notifications\Notification;
use Illuminate\Validation\ValidationException;

trait RejectsDuplicateCategory
{
    /**
     * Category slugs are generated by the model only when it is saved. Check
     * the generated value here first so a normal duplicate submission stays
     * in the form instead of reaching the database constraint.
     */
    protected function rejectDuplicateCategory(?Category $record = null): void
    {
        $existingCategory = $this->findCategoryWithMatchingSlug(
            (string) ($this->data['name'] ?? ''),
            $record,
        );

        if (! $existingCategory) {
            return;
        }

        $this->showDuplicateCategoryWarning($existingCategory->name);
        $this->halt();
    }

    protected function findCategoryWithMatchingSlug(string $name, ?Category $record = null): ?Category
    {
        return Category::findByGeneratedSlug($name, $record?->getKey());
    }

    /**
     * The database unique index remains the authority if two admins submit
     * the same new category at once. Convert that rare race into the same
     * friendly validation response instead of exposing its SQL exception.
     *
     * @param  array<string, mixed>  $data
     */
    protected function throwDuplicateCategoryValidation(array $data): never
    {
        $submittedName = trim((string) ($data['name'] ?? ''));
        $existingCategory = $this->findCategoryWithMatchingSlug($submittedName);
        $existingName = $existingCategory?->name ?: $submittedName;

        $this->showDuplicateCategoryWarning($existingName);

        throw ValidationException::withMessages([
            'data.name' => $this->duplicateCategoryMessage($existingName),
        ]);
    }

    protected function showDuplicateCategoryWarning(string $existingName): void
    {
        $message = $this->duplicateCategoryMessage($existingName);

        $this->addError('data.name', $message);

        Notification::make()
            ->title('Category already exists')
            ->body($message)
            ->warning()
            ->send();
    }

    protected function duplicateCategoryMessage(string $existingName): string
    {
        return UniqueCategoryName::messageFor($existingName);
    }
}
